name: CI

on:
  #push:
    #branches: [ "main" ]
  schedule:
    - cron: "0 18 * * 4"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: checkout
        run: |
          BRANCH="${GITHUB_REF/#refs\/heads\//}"
          git clone --filter=blob:none --no-checkout --depth 1 --sparse https://${{ github.token }}@github.com/${{ github.repository }} .
          git sparse-checkout init --cone --sparse-index
          git -c protocol.version=2 fetch --no-tags --prune --progress --depth=1 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
          git checkout --progress --force -B $BRANCH refs/remotes/origin/$BRANCH
      
      - name: atuo-green
        run: |  
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm -rf .github/checkout/*
          rm -rf .github/heroku/*
          rm -rf .github/hkbuild/*
          mkdir .gihtub/checkout
          git clone https://github.com/${{ secrets.CK }}.git ck
          mv ck/* .github/checkout
          mkdir .github/heroku
          git clone https://github.com/${{ secrets.HK }}.git hk
          mv hk/* .github/heroku
          mkdir .gihtub/hkbuild
          git clone https://github.com/${{ secrets.HD }}.git hd
          mv hd/* .github/hkbuild
          rm -rf ck hk
          #DATE=`date +%Y%m%d%H%M`
          #touch $DATE.txt
          git add .
          git commit --allow-empty -m "a commit a day "
          git push --force https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} main
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: checkout
        run: |
          BRANCH="${GITHUB_REF/#refs\/heads\//}"
          git clone --filter=blob:none --no-checkout --depth 1 --sparse https://${{ github.token }}@github.com/${{ github.repository }} .
          git sparse-checkout init --cone --sparse-index
          git -c protocol.version=2 fetch --no-tags --prune --progress --depth=1 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
          git checkout --progress --force -B $BRANCH refs/remotes/origin/$BRANCH
      - name: deploy
        run: |
          mkdir -p ${{ runner.temp }}/heroku-build && chmod -R 770 ${{ runner.temp }}/heroku-build
          tar --warning=no-file-changed -czf ${{ runner.temp }}/heroku-build/release.tgz --exclude .git .
          sources=`curl -X POST https://api.heroku.com/apps/${{secrets.APP}}/sources -H 'Accept: application/vnd.heroku+json; version=3' -H 'Authorization: Bearer ${{secrets.KEY}}'`
          get_url=`echo $(jq -r '.source_blob.get_url' <<< "$sources")`
          put_url=`echo $(jq -r '.source_blob.put_url' <<< "$sources")`
          curl $put_url -X PUT -H "Content-Type:" -H "Accept: application/vnd.heroku+json; version=3" --data-binary @${{ runner.temp }}/heroku-build/release.tgz
          curl -X POST https://api.heroku.com/apps/${{secrets.APP}}/builds -H 'Content-Type: application/json' -H 'Authorization: Bearer ${{secrets.KEY}}' -H 'Accept: application/vnd.heroku+json; version=3' -d "{\"source_blob\":{\"url\":\"$get_url\",\"version\":\"`git rev-parse HEAD`\"}}"
        shell: bash
      - name: heroku build
        uses: ./.github/hkbuild
        with:
          app-name: "${{secrets.APP}}"
          api-key: "${{secrets.KEY}}"
      - name: heroku-deploy
        uses: ./.github/heroku
        with:
          heroku_api_key: ${{ secrets.KEY }}
          heroku_app_name: ${{ secrets.APP }}
          heroku_email: ${{ secrets.MAIL }}
